name: HomeWorldPlugin
main: edu.nmt.minecraft.HomeWorldPlugin.HomeWorldPlugin
version: 1.0
softdepend: [WorldEdit, WorldGuard, Vault]
commands:
    help:
        description: get help
        usage: /help